### ISSUE TITLE
Maybe.fromJSON(Maybe.Just(1).toJSON()) TypeError: Cannot set property value of [object folktale:Data.Maybe.Just] which has only a getter

### ISSUE THREAD

**Issue by joaomilho** [origamitower/folktale#108]
Just followed the example here http://origamitower.github.io/folktale/api/en/-unknown-module-.folktale.data.maybe.fromjson.html and got this:

```
$ node -v
v7.7.1
$ cat package.json | grep folk
    "folktale": "^2.0.0-alpha3",
$ cat yarn.lock | grep folk
folktale@^2.0.0-alpha3:
$ cat node_modules/folktale/package.json| grep version
  "version": "2.0.0-alpha3",
$ node
> const Maybe = require('folktale/data/maybe');
undefined
> Maybe.fromJSON(Maybe.Just(1).toJSON())
TypeError: Cannot set property value of [object folktale:Data.Maybe.Just] which has only a getter
    at Function.assign (<anonymous>)
    at folktale:Data.Maybe.adt.fromJSON (...node_modules/folktale/core/adt/derivations/serialization.js:161:19)
    at repl:1:7
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:336:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:533:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
```

**Comment by robotlolita** [comment]
Thanks for the report :)

This has been fixed on master (https://github.com/origamitower/folktale/commit/f4026e0e585e658877b45231653dfdff7d380f23), but hasn't been published yet. I'll try to publish a new version later this week.

**Comment by joaomilho** [comment]
De nada.

**Comment by robotlolita** [comment]
v2.0.0-alpha4 has been released. Can you try it and see if it works for you?

https://github.com/origamitower/folktale/releases/tag/release%2F2.0.0-alpha4

**Comment by framp** [comment]
This has been fixed, the example is working again.
