### ISSUE TITLE
I got some errors while trying to compile Folktale

### ISSUE THREAD

**Issue by boris-marinov** [origamitower/folktale#67]
I get an error when I run the tests, due to a missing file, which I also don't see in the repo '../helpers/simple-structures'
```
Boriss-MacBook-Air:folktale borismarinov$ mocha --require babel-polyfill test/specs/control.monad.js 
module.js:338
    throw err;
    ^

Error: Cannot find module '../helpers/simple-structures'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/borismarinov/pr/folktale/test/specs/environment.js:19:16)
```

Also I get some weird error from babel, on the Future tests

```
Boriss-MacBook-Air:folktale borismarinov$ make compile-test
/Users/borismarinov/pr/folktale/node_modules/.bin/babel test/specs-src --source-map inline --out-dir test/specs
test/specs-src/control.monad.js -> test/specs/control.monad.js
test/specs-src/core.adt.js -> test/specs/core.adt.js
test/specs-src/core.fantasy-land.js -> test/specs/core.fantasy-land.js
test/specs-src/core.lambda.js -> test/specs/core.lambda.js
test/specs-src/core.object.js -> test/specs/core.object.js
Error: test/specs-src/data.future.es6: You gave us a visitor for the node type "ForAwaitStatement" but it's not a valid type
    at verify (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:196:13)
    at Object.explode (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:72:3)
    at traverse (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:77:12)
    at NodePath.traverse (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:144:25)
    at exports.default (/Users/borismarinov/pr/folktale/node_modules/babel-plugin-transform-async-to-generator/node_modules/babel-helper-remap-async-to-generator/lib/index.js:10:8)
    at PluginPass.Function (/Users/borismarinov/pr/folktale/node_modules/babel-plugin-transform-async-to-generator/lib/index.js:13:56)
    at newFn (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/borismarinov/pr/folktale/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
make: *** [compile-test] Error 1
```

**Comment by robotlolita** [comment]
Mmh, I can't reproduce this. Is that on the master branch or on the controlMonad branch? Could you try cleaning up the working directory and reinstalling/recompiling?

```shell
rm -rf node_modules
make clean
make test
```

**Comment by boris-marinov** [comment]
Thanks, `clean` did the trick
