### ISSUE TITLE
`make test` errors out

### ISSUE THREAD

**Issue by justin-calleja** [origamitower/folktale#92]
When I `make test` I get:

```
/Users/justin/folktale-stuff/folktale/node_modules/.bin/babel src --source-map inline --out-dir annotated
TypeError: src/core/adt/data.js: Type of property not supported: null
    at valueToLiteral (/Users/justin/folktale-stuff/folktale/node_modules/babel-plugin-transform-metamagical-comments/lib/index.js:492:269)
    at pairToProperty (/Users/justin/folktale-stuff/folktale/node_modules/babel-plugin-transform-metamagical-comments/lib/index.js:463:51)
    at Array.map (native)
    at objectToExpression (/Users/justin/folktale-stuff/folktale/node_modules/babel-plugin-transform-metamagical-comments/lib/index.js:455:45)
    at mergeMeta (/Users/justin/folktale-stuff/folktale/node_modules/babel-plugin-transform-metamagical-comments/lib/index.js:517:12)
    at metaForProperty (/Users/justin/folktale-stuff/folktale/node_modules/babel-plugin-transform-metamagical-comments/lib/index.js:558:15)
    at /Users/justin/folktale-stuff/folktale/node_modules/babel-plugin-transform-metamagical-comments/lib/index.js:657:18
    at Array.map (native)
    at PluginPass.ObjectExpression (/Users/justin/folktale-stuff/folktale/node_modules/babel-plugin-transform-metamagical-comments/lib/index.js:656:36)
    at newFn (/Users/justin/folktale-stuff/folktale/node_modules/babel-traverse/lib/visitors.js:276:21)
make: *** [compile-annotated] Error 1
```

### Environment

(Describe the environment where the problem happens. This usually includes:

  - OS mac
  - node v6.3.1 or  v7.7.3
  - Folktale master

**Comment by robotlolita** [comment]
Sorry, the contributor documentation was quite outdated.

Some tools are in a git submodule now, and if you install them from npm there'll be some features missing that break the build. The right way to configure the repository is by initialising the submodules, then running `make tools`. Pretty much:

```shell
npm install
git submodule init
git submodule update
make tools
```

From there on, `make test` should work.

See the [Implementing your changes](https://github.com/origamitower/folktale/blob/patch/contributor-docs/CONTRIBUTING.md#implementing-your-changes) section of the contributor documentation for more details.

**Comment by justin-calleja** [comment]
@robotlolita thanks sry didn't see that before.

**Comment by robotlolita** [comment]
No worries. It wasn't there before, though, I just updated it :)
